# Generated by Django 6.0.4 on 2026-04-23 15:32

import django.db.models.deletion
import tracker.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                (
                    "focus",
                    models.CharField(
                        choices=[
                            ("aerobic", "Aerobic"),
                            ("strength", "Strength"),
                            ("mobility", "Mobility"),
                            ("balance", "Balance"),
                            ("hybrid", "Hybrid"),
                        ]
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "activities",
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("duration_minutes", models.IntegerField(default=0)),
                ("dystonia_present", models.BooleanField(default=False)),
                (
                    "dystonia_severity",
                    tracker.fields.SeverityField(
                        blank=True,
                        choices=[
                            (0, "None"),
                            (1, "Mild"),
                            (2, "Mild-Moderate"),
                            (3, "Moderate"),
                            (4, "Moderate-Severe"),
                            (5, "Severe"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "dystonia_onset",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracker.activity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
                (
                    "pain",
                    tracker.fields.SeverityField(
                        choices=[
                            (0, "None"),
                            (1, "Mild"),
                            (2, "Mild-Moderate"),
                            (3, "Moderate"),
                            (4, "Moderate-Severe"),
                            (5, "Severe"),
                        ]
                    ),
                ),
                (
                    "rigidity",
                    tracker.fields.SeverityField(
                        choices=[
                            (0, "None"),
                            (1, "Mild"),
                            (2, "Mild-Moderate"),
                            (3, "Moderate"),
                            (4, "Moderate-Severe"),
                            (5, "Severe"),
                        ]
                    ),
                ),
                (
                    "bradykinesia",
                    tracker.fields.SeverityField(
                        choices=[
                            (0, "None"),
                            (1, "Mild"),
                            (2, "Mild-Moderate"),
                            (3, "Moderate"),
                            (4, "Moderate-Severe"),
                            (5, "Severe"),
                        ]
                    ),
                ),
                (
                    "tremor",
                    tracker.fields.SeverityField(
                        choices=[
                            (0, "None"),
                            (1, "Mild"),
                            (2, "Mild-Moderate"),
                            (3, "Moderate"),
                            (4, "Moderate-Severe"),
                            (5, "Severe"),
                        ]
                    ),
                ),
                (
                    "hand_dysfunction",
                    tracker.fields.SeverityField(
                        choices=[
                            (0, "None"),
                            (1, "Mild"),
                            (2, "Mild-Moderate"),
                            (3, "Moderate"),
                            (4, "Moderate-Severe"),
                            (5, "Severe"),
                        ]
                    ),
                ),
                (
                    "fatigue",
                    tracker.fields.SeverityField(
                        choices=[
                            (0, "None"),
                            (1, "Mild"),
                            (2, "Mild-Moderate"),
                            (3, "Moderate"),
                            (4, "Moderate-Severe"),
                            (5, "Severe"),
                        ]
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("dose", models.CharField()),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "name", "dose")},
            },
        ),
        migrations.CreateModel(
            name="MedicationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracker.medication",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
