# Generated by Django 6.0.4 on 2026-04-27 02:33

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


COUNT_CORRECT_CHARS_SQL = """
    CREATE OR REPLACE FUNCTION count_correct_chars(prompt TEXT, typed TEXT)
    RETURNS INTEGER
    IMMUTABLE
    AS $$
    DECLARE
        correct_count INTEGER := 0;
        min_length INTEGER := LEAST(LENGTH(prompt), LENGTH(typed));
    BEGIN
        FOR i IN 1..min_length LOOP
            IF SUBSTRING(prompt, i, 1) = SUBSTRING(typed, i, 1) THEN
                correct_count := correct_count + 1;
            END IF;
        END LOOP;
        RETURN correct_count;
    END;
    $$ LANGUAGE plpgsql;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0002_tappingtest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            COUNT_CORRECT_CHARS_SQL,
            reverse_sql="DROP FUNCTION IF EXISTS count_correct_chars(TEXT, TEXT);",
        ),
        migrations.CreateModel(
            name="TypingTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("prompt", models.TextField()),
                ("typed", models.TextField()),
                ("time_seconds", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "correct_chars",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Func(
                            models.F("prompt"),
                            models.F("typed"),
                            function="count_correct_chars",
                        ),
                        output_field=models.IntegerField(),
                    ),
                ),
                (
                    "errors",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            django.db.models.functions.text.Length("typed"),
                            "-",
                            models.Func(
                                models.F("prompt"),
                                models.F("typed"),
                                function="count_correct_chars",
                            ),
                        ),
                        output_field=models.IntegerField(),
                    ),
                ),
                (
                    "accuracy",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(then=0, typed=""),
                            default=django.db.models.expressions.CombinedExpression(
                                django.db.models.expressions.CombinedExpression(
                                    models.Func(
                                        models.F("prompt"),
                                        models.F("typed"),
                                        function="count_correct_chars",
                                    ),
                                    "*",
                                    models.Value(100.0),
                                ),
                                "/",
                                django.db.models.functions.text.Length("typed"),
                            ),
                            output_field=models.DecimalField(
                                decimal_places=2, max_digits=5
                            ),
                        ),
                        output_field=models.DecimalField(
                            decimal_places=2, max_digits=5
                        ),
                    ),
                ),
                (
                    "wpm",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.Func(
                                    models.F("prompt"),
                                    models.F("typed"),
                                    function="count_correct_chars",
                                ),
                                "/",
                                models.Value(5.0),
                            ),
                            "/",
                            django.db.models.expressions.CombinedExpression(
                                models.F("time_seconds"), "/", models.Value(60.0)
                            ),
                        ),
                        output_field=models.DecimalField(
                            decimal_places=2, max_digits=5
                        ),
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
