# Generated by Django 6.0.4 on 2026-04-27 15:38

import tracker.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0003_typingtest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activitylog",
            name="dystonia_present",
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="duration_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="dystonia_onset",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="dystonia_severity",
            field=tracker.fields.SeverityField(
                choices=[
                    (0, "None"),
                    (1, "Mild"),
                    (2, "Mild-Moderate"),
                    (3, "Moderate"),
                    (4, "Moderate-Severe"),
                    (5, "Severe"),
                ],
                default=0,
            ),
        ),
        migrations.AddConstraint(
            model_name="activitylog",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration_minutes__gte", 0)),
                name="duration_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="activitylog",
            constraint=models.CheckConstraint(
                condition=models.Q(("dystonia_severity__gte", 0)),
                name="dystonia_severity_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="activitylog",
            constraint=models.CheckConstraint(
                condition=models.Q(("dystonia_onset__gte", 0)),
                name="dystonia_onset_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="activitylog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("dystonia_onset__gt", 0), ("dystonia_severity", 0), _negated=True
                ),
                name="dystonia_onset_without_severity",
            ),
        ),
    ]
