# Generated by Django 6.0.4 on 2026-04-30 22:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0004_remove_activitylog_dystonia_present_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checkin",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="medicationlog",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="tappingtest",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="typingtest",
            options={"ordering": ["-timestamp"]},
        ),
    ]
