# Generated by Django 6.0.4 on 2026-05-01 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_checkin_options_alter_medicationlog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checkin',
            unique_together={('user', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='medicationlog',
            unique_together={('user', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='tappingtest',
            unique_together={('user', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='typingtest',
            unique_together={('user', 'timestamp')},
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('activity_type', models.CharField()),
                ('data', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'abstract': False,
                'unique_together': {('user', 'timestamp')},
            },
        ),
    ]
