# Generated by Django 6.0.4 on 2026-05-01 15:35

import django.db.models.deletion
import tracker.fields
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    ActivityLog = apps.get_model("tracker", "ActivityLog")
    Workout = apps.get_model("tracker", "Workout")
    ExerciseDystonia = apps.get_model("tracker", "ExerciseDystonia")
    dystonia = []
    for log in ActivityLog.objects.filter(
        activity__name__iexact="running", dystonia_onset__gt=0
    ):
        workout = Workout.objects.get(
            user=log.user,
            timestamp__date=log.timestamp.date(),
            activity_type="running",
        )
        dystonia.append(
            ExerciseDystonia(
                workout=workout,
                onset_minutes=log.dystonia_onset,
                severity=log.dystonia_severity,
                notes=log.notes,
            )
        )
    ExerciseDystonia.objects.bulk_create(dystonia)


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0006_alter_checkin_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="ExerciseDystonia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("onset_minutes", models.PositiveSmallIntegerField()),
                (
                    "severity",
                    tracker.fields.SeverityField(
                        choices=[
                            (0, "None"),
                            (1, "Mild"),
                            (2, "Mild-Moderate"),
                            (3, "Moderate"),
                            (4, "Moderate-Severe"),
                            (5, "Severe"),
                        ],
                        default=0,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "workout",
                    models.OneToOneField(
                        limit_choices_to={"activity_type": "running"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracker.workout",
                    ),
                ),
            ],
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
