# Generated by Django 6.0.4 on 2026-05-01 15:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0007_workout_notes_exercisedystonia"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="activity",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="activity",
            name="user",
        ),
        migrations.RemoveConstraint(
            model_name="activitylog",
            name="duration_non_negative",
        ),
        migrations.RemoveConstraint(
            model_name="activitylog",
            name="dystonia_severity_non_negative",
        ),
        migrations.RemoveConstraint(
            model_name="activitylog",
            name="dystonia_onset_non_negative",
        ),
        migrations.RemoveConstraint(
            model_name="activitylog",
            name="dystonia_onset_without_severity",
        ),
        migrations.RemoveField(
            model_name="activitylog",
            name="activity",
        ),
        migrations.RemoveField(
            model_name="activitylog",
            name="user",
        ),
        migrations.DeleteModel(
            name="Activity",
        ),
        migrations.DeleteModel(
            name="ActivityLog",
        ),
    ]
