# Generated by Django 6.0.4 on 2026-05-03 12:09

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0009_healthmetric"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkin",
            name="overall_severity",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    django.db.models.expressions.CombinedExpression(
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                django.db.models.expressions.CombinedExpression(
                                    django.db.models.expressions.CombinedExpression(
                                        django.db.models.expressions.CombinedExpression(
                                            models.Value(0), "+", models.F("pain")
                                        ),
                                        "+",
                                        models.F("rigidity"),
                                    ),
                                    "+",
                                    models.F("bradykinesia"),
                                ),
                                "+",
                                models.F("tremor"),
                            ),
                            "+",
                            models.F("hand_dysfunction"),
                        ),
                        "+",
                        models.F("fatigue"),
                    ),
                    "/",
                    models.Value(6),
                ),
                output_field=models.DecimalField(decimal_places=2, max_digits=4),
            ),
        ),
    ]
