# Generated by Django 6.0.4 on 2026-05-03 12:38

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0010_checkin_overall_severity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tappingtest",
            name="taps_per_second",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    models.F("taps"), "/", models.F("duration")
                ),
                output_field=models.DecimalField(decimal_places=2, max_digits=5),
            ),
        ),
        migrations.AddConstraint(
            model_name="tappingtest",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration__gt", 0)), name="duration_positive"
            ),
        ),
    ]
