# Generated by Django 6.0.4 on 2026-05-03 17:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0011_tappingtest_taps_per_second_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tappingtest",
            name="taps_per_second",
        ),
    ]
