# Generated by Django 6.0.4 on 2026-05-06 01:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0012_remove_tappingtest_taps_per_second"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkin",
            name="overall_severity",
        ),
    ]
