# Generated by Django 6.0.4 on 2026-05-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0014_checkin_overall_severity"),
    ]

    operations = [
        migrations.AddField(
            model_name="medication",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
