# Generated by Django 6.0.4 on 2026-05-10 19:57

import tracker.fields
from django.db import migrations


def update_severity_choices(apps, schema_editor):
    CheckIn = apps.get_model("tracker", "CheckIn")
    ExerciseDystonia = apps.get_model("tracker", "ExerciseDystonia")

    checkins = []
    fields_to_update = [
        "bradykinesia",
        "fatigue",
        "hand_dysfunction",
        "pain",
        "rigidity",
        "tremor",
    ]
    for checkin in CheckIn.objects.all():
        for field in fields_to_update:
            value = getattr(checkin, field)
            value = min(value, 4)  # Cap the value at 4 (Severe)
            setattr(checkin, field, value)
        checkins.append(checkin)
    CheckIn.objects.bulk_update(checkins, fields_to_update)

    exercise_dystonias = []
    for dystonia in ExerciseDystonia.objects.all():
        value = dystonia.severity
        value = min(value, 4)  # Cap the value at 4 (Severe)
        dystonia.severity = value
        exercise_dystonias.append(dystonia)
    ExerciseDystonia.objects.bulk_update(exercise_dystonias, ["severity"])


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0015_medication_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkin",
            name="bradykinesia",
            field=tracker.fields.SeverityField(
                choices=[
                    (0, "Normal"),
                    (1, "Slight"),
                    (2, "Mild"),
                    (3, "Moderate"),
                    (4, "Severe"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="fatigue",
            field=tracker.fields.SeverityField(
                choices=[
                    (0, "Normal"),
                    (1, "Slight"),
                    (2, "Mild"),
                    (3, "Moderate"),
                    (4, "Severe"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="hand_dysfunction",
            field=tracker.fields.SeverityField(
                choices=[
                    (0, "Normal"),
                    (1, "Slight"),
                    (2, "Mild"),
                    (3, "Moderate"),
                    (4, "Severe"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="pain",
            field=tracker.fields.SeverityField(
                choices=[
                    (0, "Normal"),
                    (1, "Slight"),
                    (2, "Mild"),
                    (3, "Moderate"),
                    (4, "Severe"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="rigidity",
            field=tracker.fields.SeverityField(
                choices=[
                    (0, "Normal"),
                    (1, "Slight"),
                    (2, "Mild"),
                    (3, "Moderate"),
                    (4, "Severe"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="tremor",
            field=tracker.fields.SeverityField(
                choices=[
                    (0, "Normal"),
                    (1, "Slight"),
                    (2, "Mild"),
                    (3, "Moderate"),
                    (4, "Severe"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="exercisedystonia",
            name="severity",
            field=tracker.fields.SeverityField(
                choices=[
                    (0, "Normal"),
                    (1, "Slight"),
                    (2, "Mild"),
                    (3, "Moderate"),
                    (4, "Severe"),
                ],
                default=0,
            ),
        ),
        migrations.RunPython(update_severity_choices),
    ]
